server {
	listen 80 default_server;

	server_name _;

	location /.well-known/acme-challenge {
		root /var/www/certbot;
	}

	location / {
		return 301 https://$host$request_uri;
	}
}

server {
	listen 443 ssl;
	server_name winecraft.dev; 
	
	ssl_certificate /etc/letsencrypt/live/winecraft.dev/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/winecraft.dev/privkey.pem;

	location / {
		proxy_pass http://winecraft:8080;
	}
}

server {
	listen 443 ssl;
	server_name connect4.winecraft.dev;

	ssl_certificate /etc/letsencrypt/live/connect4.winecraft.dev/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/connect4.winecraft.dev/privkey.pem;

	location / {
		proxy_pass http://connect4:8080;
		proxy_http_version 1.1;

		# WebSocket support
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

		# Forward host/IP info
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}

server {
	listen 443 ssl;
	server_name jellothompson.com; 
	
	ssl_certificate /etc/letsencrypt/live/jellothompson.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/jellothompson.com/privkey.pem;

	location / {
		proxy_pass http://jello:8080;
	}
}
